if __name__ == '__main__':
    # WeeklyChallenge.Answer.week1.main()
    # WeeklyChallenge.Answer.week2.main()
    # WeeklyChallenge.Answer.week4.main()
    # WeeklyChallenge.Answer.week5.main()
    # WeeklyChallenge.Answer.week6.main()
    # WeeklyChallenge.Answer.week7.main()
    # WeeklyChallenge.Answer_Improved.week1_improved.main()
    # WeeklyChallenge.Answer_Improved.week2_improved.main()
    # WeeklyChallenge.Answer_Improved.week4_improved.main()
    # WeeklyChallenge.Answer_Improved.week5_improved.main()
    # WeeklyChallenge.Answer_Improved.week6_improved.main()
    Python.WeeklyChallenge.Answer_Improved.week7_improved.main()